### ISSUE TITLE
Not able to execute the force-source-convert command

### ISSUE THREAD

**Issue by saisandeepc** [mcartoixa/ant-sfdx#2]
Not able to execute the force-source-convert command getting error as 
BUILD FAILED
C:\SaiSandeep\POCBuildProcess\build\build.xml:20: Problem: failed to create task or type force-source-convert
Cause: The name is undefined.

Error:-
![image](https://user-images.githubusercontent.com/27053441/72802000-cb1e8480-3c70-11ea-9439-3689f06adc35.png)

ant-sfdx docs:-
![image](https://user-images.githubusercontent.com/27053441/72801690-12f0dc00-3c70-11ea-9420-1648e1420f04.png)

**Comment by mcartoixa** [comment]
It seems that I have forgotten to link [the task implementation](../blob/v0.5/src/main/com/mcartoixa/ant/sfdx/force/source/ConvertTask.java) with [the task declaration file](https://github.com/mcartoixa/ant-sfdx/blob/v0.5/src/main/com/mcartoixa/ant/sfdx/antlib.xml). I'll fix that in a future release.

Thanks for reporting this issue.

**Comment by mcartoixa** [comment]
A few (!) commits later, the _force-source-convert_ task has been fixed in version 0.6. I have not tested it a lot but it should work alright. Please note that the task parameters have changed since the version you tried.

Please also note that the task output is very minimalistic. Please ping me again if you have any ideas about that (and bring a JSON output with you..).
